### ISSUE TITLE
Ejercicios

### ISSUE THREAD

**Issue by josealfredo79** [SistemasTecTlaxiaco/Equipo-X-Practica#2]
Aqui debe ir los ejercicios y evaluar de acuerdo con la rubrica y su respectiva calificación

**Comment by josealfredo79** [comment]
Nuevamente insisto que aqui debe ir la informacion

**Comment by josealfredo79** [comment]
Aqui deben ir los ejercicios y la calificación

**Comment by RicardoMtzSts** [comment]
excelente trabajo 20/20

**Comment by irving1613** [comment]
[Operaciones Basicas - Irving Zárate Reyes.pdf](https://github.com/SistemasTecTlaxiaco/ejercicios-equipo-erick-ramos/files/7221958/Operaciones.Basicas.-.Irving.Zarate.Reyes.pdf)

**Comment by 7177981** [comment]
Muy buen trabajo, y resueltos de manera correcta 20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado

**Comment by josealfredo79** [comment]
No se reviso de acuerdo a rubrica, hace falta objetivo, material, procedimiento, lista de figuras

**Comment by josealfredo79** [comment]
No se hace el trabajo por entregar
